config/routes.rb
Rails.application.routes.draw do

  resources :items
  resources :businesses

  devise_for :users do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end


  get    'businesses/index'
  get    'businesses/new'


  post '/api/login' => 'api#login'


  #get    '/signup',       to: 'users#new'

  #get    '/login',        to: 'sessions#new'
  #post   '/login',        to: 'sessions#create'
  #delete '/logout',       to: 'sessions#destroy'

  root 'home#index'

end

app/controllers/businesses_controller.rb
class BusinessesController < ApplicationController
  before_action :set_business, only: [:show, :edit, :update, :destroy]

  # GET /businesses
  def index
   
    if current_business.present?
      @businesses = Business.where("id = ? ",current_user.id).all

      # @items = Item.all
     else
 
     # If business not yet created, redirect to create a new business
       redirect_to new_business_path, notice: "Please create a business."
     end

  end

  # GET /businesses/1
  def show
  end

  # GET /businesses/new
  def new
    @business = Business.new
  end

  # GET /businesses/1/edit
  def edit
  end

  # POST /businesses
  def create
    @business = Business.new(business_params)

    if @business.save
      redirect_to @business, notice: 'Business was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /businesses/1
  def update
    if @business.update(business_params)
      redirect_to @business, notice: 'Business was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /businesses/1
  def destroy
    @business.destroy
    redirect_to businesses_url, notice: 'Business was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_business
      @business = Business.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def business_params
        defaults = {user_id: current_user.id}
        params.require(:business).permit(:name, :address, :city, :user_id).reverse_merge(defaults)
    end
end

app/helpers/businesses_helper.rb
module BusinessesHelper
end

app/views/businesses/_form.html.erb
<%= form_with(model: business, local: true) do |form| %>
  <% if business.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(business.errors.count, "error") %> prohibited this business from being saved:</h2>

      <ul>
      <% business.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row">
    <div class="col-lg-12 col-sm-12">
      <%= form.label :name, "* Name" %>
      <%= form.text_field :name, class: "form-control", required: true%>
    </div>
  </div>

  <div class="row">
    <div class="col-lg-6 col-sm-12">
      <%= form.label :address, "* Address" %>
      <%= form.text_field :address, class: "form-control", required: true%>
    </div>

    <div class="col-lg-6 col-sm-12">
      <%= form.label :city, "* City" %>
      <%= form.text_field :city, class: "form-control", required: true%>
    </div>
  </div>
<br>
  <div class="actions">
    <%= form.submit "Save", class: "btn btn-primary", style: "width: 80px !important; height: 40px !important;"  %>
  </div>
<% end %>

app/views/businesses/edit.html.erb
<h1>Editing Business</h1>

<%= render 'form', business: @business %>

<%= link_to 'Show', @business %> |
<%= link_to 'Back', businesses_path %>

app/views/businesses/index.html.erb
<h1>Businesses</h1>
<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Address</th>
      <th>City</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @businesses.each do |business| %>
      <tr>
        <td><%=business.name%></td>
        <td><%=business.address%></td>
        <td><%=business.city%></td>
        <td><%= link_to 'Show', business %></td>
        <td><%= link_to 'Edit', edit_business_path(business) %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= link_to 'Back', items_path %>

<br>

app/views/businesses/new.html.erb
<h1>New Business</h1>

<%= render 'form', business: @business %>

<%= link_to 'Back', items_path %>

app/views/businesses/show.html.erb
<p>
    <strong>Name:</strong>
    <%= @business.name%>
</p>

<p>
    <strong>Address:</strong>
    <%= @business.address %>
</p>

<p>
    <strong>City:</strong>
    <%= @business.city %>
</p>
  


<%= link_to 'Edit', edit_business_path(@business) %> |
<%= link_to 'Back', businesses_path %>