config/routes.rb
Rails.application.routes.draw do

  resources :items
  resources :businesses

  devise_for :users do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end


  get    'businesses/index'
  get    'businesses/new'


  post '/api/login' => 'api#login'


  #get    '/signup',       to: 'users#new'

  #get    '/login',        to: 'sessions#new'
  #post   '/login',        to: 'sessions#create'
  #delete '/logout',       to: 'sessions#destroy'

  root 'home#index'

end

app/models/item.rb
class Item < ActiveRecord::Base
  belongs_to :business
  validates :name, presence: true
  validates :price, presence: true,:numericality => { :greater_than_or_equal_to => 0, :other_than => 0  }
  

  
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: [:show, :edit, :update, :destroy]

  def index
    # List all of the Items that are owned by the logged in User's Business
    if current_business.present?
       @items = Item.where("business_id = ?", current_business.id)
       @item = Item.new
     # @items = Item.all

    else

    # If business not yet created, redirect to create a new business
      redirect_to new_business_path, notice: "Please create a business."
    end

    

  end

  def new
      @item = Item.new
  end

  def edit

  end

  def create
    # TODO: [TAKI-001] Finish the implementation of Create/Update/Delete for Items
    @item = Item.new(item_params)

    respond_to do |format|
      if @item.save
        format.html { redirect_to @item, notice: 'Person was successfully created.' }
        format.json { render action: 'show', status: :created, location: @item }
        format.js   { render 'show', location: @item }
      else
        format.html { render :new }
        format.json { render json: @item.errors, status: :unprocessable_entity }
        format.js { render json: @item.errors, status: :unprocessable_entity }

      end
    end

  end

  def show


  end

  def update
    # TODO: [TAKI-001] Finish the implementation of Create/Update/Delete for Items
    respond_to do |format|
      if @item.update(item_params)
        format.html { redirect_to @item, notice: 'Item was successfully updated.' }
        format.json { render :show, status: :ok, location: @item }
      else
        format.html { render :edit }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    # TODO: [TAKI-001] Finish the implementation of Create/Update/Delete for Items
    @item.destroy
    respond_to do |format|
      format.html { redirect_to items_path, notice: 'Item detalhe was successfully destroyed.' }
      format.json { head :no_content }
      format.js   { render 'show', location: @item }
    end
  end

  private


  def set_item
    @item = Item.find(params[:id])
  end

  def item_params
    defaults = {business_id: current_business.id}
    params.require(:item).permit(:name, :price, :user_id).reverse_merge(defaults)
  end


end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_form.html.erb
<% modal ||= false %>
<% remote = modal ? true : false %>
<%
if(modal == true)
@item = Item.new
end
%>
<%= form_for(@item, remote: remote, html: {role: :form, 'data-model' => 'items'}) do |form| %>

 <% if @item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@item.errors.count, "error") %> prohibited this item from being saved:</h2>

      <ul>
      <% @item.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<div class="row">
    <div class="col-lg-6 col-sm-12">
        <%= form.label :name, "* Name" %>
        <%= form.text_field :name, class: "form-control input_modal", required: true%>
    </div>

    <div class="col-lg-6 col-sm-12">
        <%= form.label :price, "* Price" %>
        <%= form.text_field :price, class: "form-control input_modal money", required: true%>
    </div>
</div>

<br>

<div class="row">

    <div class="col-lg-6 col-sm-12">
        <%= form.submit "Save", class: "btn btn-primary btn-sm", style: "width: 80px !important; height: 40px !important;", remote: true%>
    </div>

</div>

<%end%>

app/views/items/_table_row.html.erb
<tr>
    <td><%= item.name %></td>
    <td><%= item.price %></td>
    <td><%= link_to '<i class="fas fa-eye"></i> Show'.html_safe, item %></td>
    <td><%= link_to '<i class="fas fa-edit"></i> Edit'.html_safe, edit_item_path(item) %></td>
    <td><%= link_to '<i class="fas fa-trash"></i> Destroy'.html_safe, item, method: :delete, data: { confirm: 'Are you sure?' } %></td>

  </tr>

app/views/items/edit.html.erb
<h1>Edit Item</h1>

<%= render 'form', item: @item%>



<%= link_to 'Show', @item %> |
<%= link_to 'Back', items_path %>

app/views/items/index.html.erb
<% provide(:title, "Items") %>

<h1>Listing items</h1>
<table class='table' id='items_table'>
  <thead>
    <tr>
      <th>Item name</th>
      <th>Price</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @items.each do |item| %>
      <%# Render table row partial for each person object %>
      <%= render partial: 'table_row', locals: {item: item} %>
    <% end %>
  </tbody>
</table>

<br>
<button type="button" class="btn btn-primary" data-toggle="modal" data-target="#new_item_modal">
<i class="fas fa-plus"></i> Add
</button>





  <div id="new_item_modal" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">

  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">New Item</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <%= render 'form',item: @item, modal: true %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

app/views/items/new.html.erb
<h1>New Item</h1>
<%= render 'form', item: @item %>

app/views/items/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @item.name%>
</p>

<p>
  <strong>Price:</strong>
  <%= @item.price %>
</p>


<%= link_to 'Edit', edit_item_path(@item) %> |
<%= link_to 'Back', items_path %>

app/views/items/show.js.erb
$(".input_modal").val("");
$('#items_table').append("<%= j render partial: 'table_row', locals: {item: @item } %>");
$('#new_item_modal').modal_success();