config/routes.rb
Rails.application.routes.draw do

  resources :items
  resources :businesses

  devise_for :users do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end


  get    'businesses/index'
  get    'businesses/new'


  post '/api/login' => 'api#login'


  #get    '/signup',       to: 'users#new'

  #get    '/login',        to: 'sessions#new'
  #post   '/login',        to: 'sessions#create'
  #delete '/logout',       to: 'sessions#destroy'

  root 'home#index'

end

app/views/layouts/_footer.html.erb
<footer class="footer">
  
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <a href="/"><h2 class="header-main"><i class="fas fa-shopping-cart"></i> Taki Rails Interview </h2></a>
<nav class="navbar navbar-expand-sm navbar-light bg-light">
   <div class="collapse navbar-collapse" id="navbarTogglerDemo01">
    <ul class="nav navbar-nav navbar-right">
      <% if current_user %>
        <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
          <li class="nav-item"><%= link_to '<i class="fas fa-building"></i> Create Business'.html_safe, new_business_path %></li>
          <li class="nav-item">          
            <a href="/users/edit" class="nav-link" data-method="get">
              <i class="fas fa-user-edit"></i> Edit Profile
            </a>
          </li>
          <li class="divider"></li>
          <li class="nav-item">
            <%# link_to "Log out", logout_path, method: "delete" %>
            <a href="/users/sign_out" " data-method="get">
              <i class="fas fa-sign-out-alt"></i> Log out
          </a>
          </li>
        </ul>
      <% end %>
    </ul>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Taki Rails Interview</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script src="https://ajax.googleapis.com/ajax/libs/d3js/5.15.1/d3.min.js"></script>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.mask/1.14.16/jquery.mask.min.js" type="text/javascript"></script>
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" integrity="sha384-gfdkjb5BdAXd+lj+gudLWI+BXq4IuLW5IT+brZEZsLFm++aCMlF1V92rMkPaX4PP" crossorigin="anonymous">

  </head>
  <body>

  <%= render 'layouts/header' %>

  <div class="container">
    <!-- flash message -->
    <% if notice.present? %>
      <p id="notice"><%= notice %></p>
    <% end %>

    <% if alert.present? %>
      <p id="alert"><%= alert %></p>
    <% end %>


    <%= yield %>
  </div>

  <%= render 'layouts/footer' %>

  </body>
</html>